In [2]:
import numpy as np

In [3]:
dataset = np.genfromtxt('../../data/StudentsPerformance.csv', 
                        delimiter=',', 
                        skip_header=1, 
                        dtype=int)
dataset

array([[-1, -1, -1, ..., 72, 72, 74],
       [-1, -1, -1, ..., 69, 90, 88],
       [-1, -1, -1, ..., 90, 95, 93],
       ...,
       [-1, -1, -1, ..., 59, 71, 65],
       [-1, -1, -1, ..., 68, 78, 77],
       [-1, -1, -1, ..., 77, 86, 86]])

In [4]:
write_scores = dataset[:, -1]
read_scores = dataset[:, -2]
math_scores = dataset[:, -3]

## Estadísticas

In [5]:
# ...

## Categóricos

Cargar todas las columnas del dataset csv en arrays distintos

In [6]:
gender = np.genfromtxt('../../data/StudentsPerformance.csv', delimiter=',', skip_header=1, 
                       usecols=(0), dtype=str)
race = np.genfromtxt('../../data/StudentsPerformance.csv', delimiter=',', skip_header=1, usecols=(1),dtype=str)
parent_education = np.genfromtxt('../../data/StudentsPerformance.csv', delimiter=',', skip_header=1, usecols=(2),dtype=str)
lunch = np.genfromtxt('../../data/StudentsPerformance.csv', delimiter=',', skip_header=1, usecols=(3),dtype=str)
preparation = np.genfromtxt('../../data/StudentsPerformance.csv', delimiter=',', skip_header=1, usecols=(4),dtype=str)

Sacar valores únicos por cada columna

In [7]:
print(np.unique(gender))
print(np.unique(race))
print(np.unique(parent_education))
print(np.unique(lunch))
print(np.unique(preparation))

['female' 'male']
['group A' 'group B' 'group C' 'group D' 'group E']
["associate's degree" "bachelor's degree" 'high school' "master's degree"
 'some college' 'some high school']
['free/reduced' 'standard']
['completed' 'none']


Moda

In [8]:
from scipy import stats

In [9]:
print(stats.mode(gender, keepdims=True))
print(stats.mode(race, keepdims=True))
print(stats.mode(parent_education, keepdims=True))
print(stats.mode(lunch, keepdims=True))
print(stats.mode(preparation, keepdims=True))

ModeResult(mode=array(['female'], dtype='<U6'), count=array([518]))
ModeResult(mode=array(['group C'], dtype='<U7'), count=array([319]))
ModeResult(mode=array(['some college'], dtype='<U18'), count=array([226]))
ModeResult(mode=array(['standard'], dtype='<U12'), count=array([645]))
ModeResult(mode=array(['none'], dtype='<U9'), count=array([642]))


C:\Users\funda\AppData\Local\Temp\ipykernel_6480\2006625649.py:1: DeprecationWarning: Support for non-numeric arrays has been deprecated as of SciPy 1.9.0 and will be removed in 1.11.0. `pandas.DataFrame.mode` can be used instead, see https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mode.html.
  print(stats.mode(gender, keepdims=True))
C:\Users\funda\AppData\Local\Temp\ipykernel_6480\2006625649.py:2: DeprecationWarning: Support for non-numeric arrays has been deprecated as of SciPy 1.9.0 and will be removed in 1.11.0. `pandas.DataFrame.mode` can be used instead, see https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mode.html.
  print(stats.mode(race, keepdims=True))
C:\Users\funda\AppData\Local\Temp\ipykernel_6480\2006625649.py:3: DeprecationWarning: Support for non-numeric arrays has been deprecated as of SciPy 1.9.0 and will be removed in 1.11.0. `pandas.DataFrame.mode` can be used instead, see https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mod

Counts

In [10]:
print(np.unique(gender, return_counts=True))
print(type(np.unique(gender, return_counts=True)))

(array(['female', 'male'], dtype='<U6'), array([518, 482], dtype=int64))
<class 'tuple'>


In [11]:
uniques, counts = np.unique(gender, return_counts=True)
counts

array([518, 482], dtype=int64)

In [12]:
# zip permite concatenar elemento a elemento de estructuras distintas
dict(zip(uniques, counts))

{'female': 518, 'male': 482}

In [13]:
# SELECT COUNT(*) from race
len(race)

1000

In [14]:
import collections

collections.Counter(race)

Counter({'group C': 319,
         'group D': 262,
         'group B': 190,
         'group E': 140,
         'group A': 89})

## Correlación

In [15]:
np.corrcoef(math_scores, read_scores)

array([[1.        , 0.81757966],
       [0.81757966, 1.        ]])

## Cuartiles y Percentiles

In [16]:
print(np.percentile(math_scores, 25))
print(np.percentile(math_scores, 50))
print(np.percentile(math_scores, 75))

57.0
66.0
77.0


In [17]:
print(np.percentile(math_scores, 10))
print(np.percentile(math_scores, 90))

47.0
86.0


In [18]:
top_10 = math_scores >= np.percentile(math_scores, 90)
math_top_10 = math_scores[top_10]
math_top_10

array([ 90,  88,  88,  97,  88,  98,  87,  99,  91,  88,  87,  89,  87,
        88,  88, 100,  96,  94,  97,  87,  87,  86,  88,  92,  89,  99,
        88,  88,  97,  88,  86,  90,  99,  90,  87,  87,  88,  87,  86,
        89,  86, 100, 100,  91,  90,  94,  95,  86,  91,  97,  92,  87,
        96,  92,  91,  92,  94,  88,  95, 100, 100,  86,  90,  94,  93,
        87,  89,  93,  98,  96,  91,  87,  92,  87,  94,  91,  89,  87,
        90,  87,  94,  90,  91,  87,  97,  87,  97,  90,  93,  86,  88,
        93,  88, 100,  91,  98,  94,  92, 100,  89,  91,  86,  88])

In [19]:
Q1 = np.percentile(math_scores, 25)
Q3 = np.percentile(math_scores, 75)

IQR = Q3 - Q1
IQR

20.0

## Reduce

In [20]:
big_array = np.random.rand(100000000)

In [21]:
%%time
suma = 0
for score in big_array:
    suma += score

print(suma)

50001766.480590835
CPU times: total: 10.9 s
Wall time: 11.1 s


In [22]:
%%time

np.add.reduce(big_array)

CPU times: total: 156 ms
Wall time: 154 ms


50001766.48055609

## Filtros

In [62]:
data = gender = np.genfromtxt('../../data/StudentsPerformance.csv', 
                              delimiter=',', 
                              skip_header=1, 
                              encoding='utf-8',
                              dtype=None,
                              usecols=(0, 1, 2, 3, 4, 5, 6, 7))
data[:10]

C:\Users\funda\AppData\Local\Temp\ipykernel_6480\80212930.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  data = gender = np.genfromtxt('../../data/StudentsPerformance.csv',


array([(b'female', b'group B', b"bachelor's degree", b'standard', b'none', 72, 72, 74),
       (b'female', b'group C', b'some college', b'standard', b'completed', 69, 90, 88),
       (b'female', b'group B', b"master's degree", b'standard', b'none', 90, 95, 93),
       (b'male', b'group A', b"associate's degree", b'free/reduced', b'none', 47, 57, 44),
       (b'male', b'group C', b'some college', b'standard', b'none', 76, 78, 75),
       (b'female', b'group B', b"associate's degree", b'standard', b'none', 71, 83, 78),
       (b'female', b'group B', b'some college', b'standard', b'completed', 88, 95, 92),
       (b'male', b'group B', b'some college', b'free/reduced', b'none', 40, 43, 39),
       (b'male', b'group D', b'high school', b'free/reduced', b'completed', 64, 64, 67),
       (b'female', b'group B', b'high school', b'free/reduced', b'none', 38, 60, 50)],
      dtype=[('f0', 'S6'), ('f1', 'S7'), ('f2', 'S18'), ('f3', 'S12'), ('f4', 'S9'), ('f5', '<i4'), ('f6', '<i4'), ('f7', '<i4')

In [55]:
print(data.ndim)
print(data.shape)

2
(1000, 8)


In [68]:
data['f1'][:5]

array([b'group B', b'group C', b'group B', b'group A', b'group C'],
      dtype='|S7')

In [66]:
def filter_by_race(data, race_group):
    return data[data['f1'] == race_group]

In [67]:
filter_by_race(data, 'group C')

C:\Users\funda\AppData\Local\Temp\ipykernel_6480\1802360292.py:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return data[data['f1'] == race_group]


array([], shape=(0, 1000),
      dtype=[('f0', 'S6'), ('f1', 'S7'), ('f2', 'S18'), ('f3', 'S12'), ('f4', 'S9'), ('f5', '<i4'), ('f6', '<i4'), ('f7', '<i4')])

In [ ]:
# ordenar descendente por math_score
indices = np.argsort(math_scores)[::-1]
data[indices]