In [1]:
import numpy as np

In [4]:
total_bill = np.genfromtxt('../../data/tips.csv', 
                           delimiter=',', skip_header=1, 
                           usecols=(0), dtype=float)
tip = np.genfromtxt('../../data/tips.csv', 
                           delimiter=',', skip_header=1, 
                           usecols=(1), dtype=float)
genre = np.genfromtxt('../../data/tips.csv', 
                           delimiter=',', skip_header=1, 
                           usecols=(2), dtype=str)
smoker = np.genfromtxt('../../data/tips.csv', 
                           delimiter=',', skip_header=1, 
                           usecols=(3), dtype=str)
day = np.genfromtxt('../../data/tips.csv', 
                           delimiter=',', skip_header=1, 
                           usecols=(4), dtype=str)
time = np.genfromtxt('../../data/tips.csv', 
                           delimiter=',', skip_header=1, 
                           usecols=(5), dtype=str)
size = np.genfromtxt('../../data/tips.csv', 
                           delimiter=',', skip_header=1, 
                           usecols=(6), dtype=int)

In [7]:
print(total_bill[:5])
print(tip[:5])
print(genre[:5])
print(smoker[:5])
print(day[:5])
print(time[:5])
print(size[:5])

[16.99 10.34 21.01 23.68 24.59]
[1.01 1.66 3.5  3.31 3.61]
['Female' 'Male' 'Male' 'Male' 'Female']
['No' 'No' 'No' 'No' 'No']
['Sun' 'Sun' 'Sun' 'Sun' 'Sun']
['Dinner' 'Dinner' 'Dinner' 'Dinner' 'Dinner']
[2 3 3 2 4]


## Categóricas

In [8]:
print(np.unique(genre))
print(np.unique(smoker))
print(np.unique(day))
print(np.unique(time))

['Female' 'Male']
['No' 'Yes']
['Fri' 'Sat' 'Sun' 'Thur']
['Dinner' 'Lunch']


In [11]:
import collections

print(collections.Counter(genre))
print(collections.Counter(smoker))
print(collections.Counter(day))
print(collections.Counter(time))

Counter({'Male': 157, 'Female': 87})
Counter({'No': 151, 'Yes': 93})
Counter({'Sat': 87, 'Sun': 76, 'Thur': 62, 'Fri': 19})
Counter({'Dinner': 176, 'Lunch': 68})


In [22]:
filter = np.logical_or(day == "Sat", day == "Sun")
day[filter][:5]

array(['Sun', 'Sun', 'Sun', 'Sun', 'Sun'], dtype='<U4')

In [26]:
# sabado y domingo
day[(day == "Sat") | (day == "Sun")][:5]

array(['Sun', 'Sun', 'Sun', 'Sun', 'Sun'], dtype='<U4')

In [28]:
# Negando sábado y domingo obtenemos Jueves y Viernes
day[~((day == "Sat") | (day == "Sun"))][:5]

array(['Thur', 'Thur', 'Thur', 'Thur', 'Thur'], dtype='<U4')

## Numéricas

In [37]:
from scipy import stats

In [38]:
# Columna total_bill
print(f"mean: {np.around(np.mean(total_bill), 2)}")
print(f"median: {np.median(total_bill)}")
print(f"max: {np.max(total_bill)}")
print(f"min: {np.min(total_bill)}")
print(f"std: {np.std(total_bill)}")
# print(f"mode: {stats.mode(total_bill, keepdims=True)}")

mean: 19.79
median: 17.795
max: 50.81
min: 3.07
std: 8.884150577771132
mode: ModeResult(mode=array([13.42]), count=array([3]))


In [40]:
# Columna tip
print(f"mean: {np.around(np.mean(tip), 2)}")
print(f"median: {np.median(tip)}")
print(f"max: {np.max(tip)}")
print(f"min: {np.min(tip)}")
print(f"std: {np.std(tip)}")
print(f"mode: {stats.mode(tip, keepdims=True)}")

mean: 3.0
median: 2.9
max: 10.0
min: 1.0
std: 1.3807999538298954
mode: ModeResult(mode=array([2.]), count=array([33]))


In [42]:
# Columna size
print(f"mean: {np.around(np.mean(size), 0)}")
print(f"median: {np.median(size)}")
print(f"max: {np.max(size)}")
print(f"min: {np.min(size)}")
print(f"std: {np.std(size)}")
print(f"mode: {stats.mode(size, keepdims=True)}")

mean: 3.0
median: 2.0
max: 6
min: 1
std: 0.9491488287193913
mode: ModeResult(mode=array([2]), count=array([156]))


In [44]:
len(tip)

244