## Numpy dataset bidimensional

Trabajar con dos dimensiones

Leer de URL

In [1]:
import numpy as np
import urllib

In [2]:
# https://archive-beta.ics.uci.edu/dataset/53/iris
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
response = urllib.request.urlopen(url)

data = np.genfromtxt(response, delimiter=",", usecols=(0, 1, 2, 3))
data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [3]:
print(data.ndim)
print(data.shape)

2
(150, 4)


In [4]:
# sepal length in cm
print(f"sepal length mean: {np.mean(data[:, 0])}")
print(f"sepal length median: {np.median(data[:, 0])}")
print(f"sepal length max: {np.max(data[:, 0])}")
print(f"sepal length min: {np.min(data[:, 0])}")
print(f"sepal length std: {np.std(data[:, 0])}")

sepal length mean: 5.843333333333334
sepal length median: 5.8
sepal length max: 7.9
sepal length min: 4.3
sepal length std: 0.8253012917851409


In [5]:
# sepal width in cm
print(f"sepal width mean original: {np.mean(data[:, 1])}")
print(f"sepal width mean rounded: {np.mean(data[:, 1]):.2f}")

print(f"sepal width median: {np.median(data[:, 1])}")
print(f"sepal width max: {np.max(data[:, 1])}")
print(f"sepal width min: {np.min(data[:, 1])}")
print(f"sepal width std: {np.std(data[:, 1])}")

sepal width mean original: 3.0540000000000003
sepal width mean rounded: 3.05
sepal width median: 3.0
sepal width max: 4.4
sepal width min: 2.0
sepal width std: 0.4321465800705435


In [6]:
# petal length in cm
print("petal length statistics:")
print(f"mean rounded: {np.mean(data[:, 2]):.2f}")
print(f"median: {np.median(data[:, 2]):.2f}")
print(f"max: {np.max(data[:, 2]):.2f}")
print(f"min: {np.min(data[:, 2]):.2f}")
print(f"std: {np.std(data[:, 2]):.2f}")

petal length statistics:
mean rounded: 3.76
median: 4.35
max: 6.90
min: 1.00
std: 1.76


## Búsquedas

https://refactoring.guru/refactoring/catalog

In [7]:
# Encontrar el índice de la flor con la longitud del pétalo más larga (índice 2)

PETAL_LENGTH = 2 # position

max_petal_length_index = np.argmax(data[:, PETAL_LENGTH])

max_petal_length = data[max_petal_length_index, PETAL_LENGTH] # data [0, 0]

print("Índice de la longitud del pétalo más larga:", max_petal_length_index)
print("Longitud del pétalo más larga:", max_petal_length)


Índice de la longitud del pétalo más larga: 118
Longitud del pétalo más larga: 6.9


## Ordenar

In [41]:
# ordenar por la primera columna ascendentemente indice 0
# longitudes del sépalo (índice 0)

indices = data[:, 0].argsort() # argsort devuelve índices

data[indices] # filtra por índices

array([[4.3, 3. , 1.1, 0.1],
       [4.4, 3.2, 1.3, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.6, 3.6, 1. , 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.6, 3.2, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 3. , 1.4, 0.3],
       [4.8, 3.4, 1.9, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3. , 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5. , 2. , 3.5, 1. ],
       [5. , 3.4, 1.5, 0.2],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3.6, 1.4, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.1, 2

In [21]:
np.sort(data, axis=0)  # ordena las columnas

array([[4.3, 2. , 1. , 0.1],
       [4.4, 2.2, 1.1, 0.1],
       [4.4, 2.2, 1.2, 0.1],
       [4.4, 2.2, 1.2, 0.1],
       [4.5, 2.3, 1.3, 0.1],
       [4.6, 2.3, 1.3, 0.1],
       [4.6, 2.3, 1.3, 0.2],
       [4.6, 2.3, 1.3, 0.2],
       [4.6, 2.4, 1.3, 0.2],
       [4.7, 2.4, 1.3, 0.2],
       [4.7, 2.4, 1.3, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.9, 2.5, 1.4, 0.2],
       [4.9, 2.5, 1.4, 0.2],
       [4.9, 2.5, 1.4, 0.2],
       [4.9, 2.6, 1.4, 0.2],
       [4.9, 2.6, 1.4, 0.2],
       [4.9, 2.6, 1.4, 0.2],
       [5. , 2.6, 1.4, 0.2],
       [5. , 2.6, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5.1, 2.7, 1.5, 0.2],
       [5.1, 2.8, 1.5, 0.2],
       [5.1, 2

In [23]:
np.sort(data[:, 0])

array([4.3, 4.4, 4.4, 4.4, 4.5, 4.6, 4.6, 4.6, 4.6, 4.7, 4.7, 4.8, 4.8,
       4.8, 4.8, 4.8, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 5. , 5. , 5. , 5. ,
       5. , 5. , 5. , 5. , 5. , 5. , 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1,
       5.1, 5.1, 5.2, 5.2, 5.2, 5.2, 5.3, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4,
       5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6,
       5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.9, 5.9, 5.9, 6. , 6. , 6. , 6. , 6. , 6. , 6.1, 6.1,
       6.1, 6.1, 6.1, 6.1, 6.2, 6.2, 6.2, 6.2, 6.3, 6.3, 6.3, 6.3, 6.3,
       6.3, 6.3, 6.3, 6.3, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.5, 6.5,
       6.5, 6.5, 6.5, 6.6, 6.6, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7,
       6.8, 6.8, 6.8, 6.9, 6.9, 6.9, 6.9, 7. , 7.1, 7.2, 7.2, 7.2, 7.3,
       7.4, 7.6, 7.7, 7.7, 7.7, 7.7, 7.9])

In [44]:
# ordenar por la primera columna descendentemente indice 0
# longitudes del sépalo (índice 0)

indices = data[:, 0].argsort() # argsort devuelve índices

data[indices][::-1] # filtra por índices

array([[7.9, 3.8, 6.4, 2. ],
       [7.7, 3. , 6.1, 2.3],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [7.7, 2.8, 6.7, 2. ],
       [7.6, 3. , 6.6, 2.1],
       [7.4, 2.8, 6.1, 1.9],
       [7.3, 2.9, 6.3, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [7.2, 3.2, 6. , 1.8],
       [7.2, 3. , 5.8, 1.6],
       [7.1, 3. , 5.9, 2.1],
       [7. , 3.2, 4.7, 1.4],
       [6.9, 3.2, 5.7, 2.3],
       [6.9, 3.1, 4.9, 1.5],
       [6.9, 3.1, 5.1, 2.3],
       [6.9, 3.1, 5.4, 2.1],
       [6.8, 3. , 5.5, 2.1],
       [6.8, 2.8, 4.8, 1.4],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.1],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3.1, 4.4, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6.7, 2.5, 5.8, 1.8],
       [6.7, 3.1, 5.6, 2.4],
       [6.7, 3.1, 4.7, 1.5],
       [6.6, 3. , 4.4, 1.4],
       [6.6, 2.9, 4.6, 1.3],
       [6.5, 3.2, 5.1, 2. ],
       [6.5, 2.8, 4.6, 1.5],
       [6.5, 3. , 5.2, 2. ],
       [6.5, 3. , 5.5, 1.8],
       [6.5, 3